// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SocialCare.DATA.Models;

public partial class Parametrizacao
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("razao_social")]
    [StringLength(255)]
    [Unicode(false)]
    public string RazaoSocial { get; set; }

    [Required]
    [Column("cnpj")]
    [StringLength(18)]
    [Unicode(false)]
    public string Cnpj { get; set; }

    [Required]
    [Column("cidade")]
    [StringLength(100)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [Required]
    [Column("bairro")]
    [StringLength(100)]
    [Unicode(false)]
    public string Bairro { get; set; }

    [Required]
    [Column("endereco")]
    [StringLength(255)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [Required]
    [Column("numero")]
    [StringLength(10)]
    [Unicode(false)]
    public string Numero { get; set; }

    [Column("email")]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("site")]
    [StringLength(255)]
    [Unicode(false)]
    public string Site { get; set; }

    [Column("telefone")]
    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [Column("logo")]
    [StringLength(255)]
    [Unicode(false)]
    public string Logo { get; set; }
}