// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SocialCare.DATA.Models;

//[Keyless]
public partial class VwCompras
{
    [Column("dataCompra", TypeName = "datetime")]
    public DateTime DataCompra { get; set; }

    [Column("id")]
    public int Id { get; set; }

    [Column("idCompra")]
    public int IdCompra { get; set; }

    [Column("idProduto")]
    public int IdProduto { get; set; }

    [Column("quantidade")]
    public int Quantidade { get; set; }

    [Column("precoUnitario", TypeName = "decimal(10, 2)")]
    public decimal PrecoUnitario { get; set; }

    [Column("subtotal", TypeName = "decimal(21, 2)")]
    public decimal? Subtotal { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }
}